name: "build-n-test"
trigger:
  branches:
    include:
      - "master"
      - "utm"
jobs:
  - job: "docker"
    strategy:
      parallel: 1
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - checkout: self
        clean: true
        lfs: true
        submodules: recursive
        persistCredentials: true
      - task: Docker@2
        inputs:
          command: build
          buildContext: "."
  - job: "build_n_test"
    strategy:
      parallel: 1
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - checkout: self
        clean: true
        lfs: true
        submodules: recursive
        persistCredentials: true
      - task: GoTool@0
        inputs:
          version: '1.17'
      - bash: |
          set -exo pipefail
          export PATH=/usr/local/go/bin:$(go env GOPATH)/bin:${PATH}
          make lint && make && make test && make test-cockroach && make test-e2e
        name: "build_and_test"
        displayName: "build_and_test"
  - job: "run_locally"
    strategy:
      parallel: 1
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - checkout: self
        clean: true
        lfs: true
        submodules: recursive
        persistCredentials: true
      - task: GoTool@0
        inputs:
          version: '1.17'
      - bash: |
          set -eo pipefail
          export PATH=/usr/local/go/bin:$(go env GOPATH)/bin:${PATH}
          make start-locally &
          while ! nc -z localhost 8082; do sleep 0.5; done
          make stop-locally
        name: "build_and_test"
        displayName: "build_and_test"

