apiVersion: v1
kind: Service
metadata:
  name: http-gateway
  namespace: {{ .Values.Namespace }}
  labels:
    app: http-gateway
  annotations:
    # Enable automatic monitoring of all instances when Prometheus is running in the cluster.
    prometheus.io/scrape: "true"
    prometheus.io/path: "_status/vars"
    prometheus.io/port: "{{ .Values.HttpPort }}"
spec:
  ports:
  - port: {{ .Values.HttpPort }}
    targetPort: {{ .Values.HttpPort }}
    name: http-gateway
  selector:
    app: http-gateway
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: http-gateway
  namespace: {{ .Values.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: http-gateway
    spec:
      containers:
      - name: http-gateway
        image: {{ .Values.GatewayImage }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.HttpPort }}
          name: http
        args:
          - -grpc-backend=grpc-backend.{{ .Values.Namespace }}:{{ .Values.GrpcPort }}
          - -addr=:{{ .Values.HttpPort }}
        readinessProbe:
          httpGet:
            path: /healthy
            port: {{ .Values.HttpPort }}
